---
name: Acceptance tests
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
jobs:
  acceptance-tests:
    name: Acceptance tests (Python ${{ matrix.python_version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Tox
        run: pip install tox
      - name: Run acceptance tests
        run: tox -e py${{ matrix.python_version }} -e acceptance
